status = WARN

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %5p [%c] %m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = CONSOLE

logger.apache-http.name = org.orbeon.private.apache.http
logger.apache-http.level = error

logger.apache-http-wire.name = org.orbeon.private.apache.http.wire
logger.apache-http-wire.level = error

logger.embedding.name = org.orbeon.embedding
logger.embedding.level = error
